language: python
env:
  - APP_MODE="config.TestConfig"
  - DATABASE_URI="N/A"
python:
  - "3.6"
# command to install dependencies and run tests
script:
  - "cd project"
  - "pip install -r requirements.txt"
  - "python manage.py test"