language: python
env:
  - APP_MODE="config.TestConfig"
  - DATABASE_URI="N/A"
python:
  - "3.6"
# command to install dependencies
install: "pip install -r project/requirements.txt"
# command to run tests
script: "python project/manage.py test"