language: python
env:
  - APP_MODE="config.TestConfig" DATABASE_URI='postgresql://docker:docker@localhost/openweather'
python:
  - "3.6"
services:
  - docker
before_install:
  - sudo service postgresql stop
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
  - cd backend2_docker; docker build -t postgresdocker .
  - docker run -dp 5432:5432 postgresdocker
script:
  - cd ..; pip install -r requirements.txt
  - cd backend_docker; python app.py &
  - cd ../frontend_docker; python manage.py test