language: python
env:
  - APP_MODE="config.TestConfig" DATABASE_URI="N/A"
python:
  - "3.6"
# command to install dependencies and run tests
before_install: cd frontend_docker
install: "pip install -r requirements.txt"
before_script: cd frontend_docker
script: "python manage.py test"