language: python
env:
  - APP_MODE="config.TestConfig" DATABASE_URI='postgresql://docker:docker@localhost/openweather'
python:
  - "3.6"
services:
  - docker
before_install:
  - cd backend2_docker; docker build -t postgresdocker .
  - cd backend2_docker; docker run -dp 5432:5432 postgresdocker
script:
  - pip install -r requirements.txt
  - cd backend_docker; python app.py &
  - cd frontend_docker; python manage.py test