language: python
env:
  - APP_MODE="config.TestConfig" DATABASE_URI="N/A"
python:
  - "3.6"
jobs:
  include:
    - stage: instal requirements
      script:
      - pip install -r requirements.txt
    - stage: start api in background
      script:
      - python backend_docker/app.py &
    - stage: test
      script:
      - python frontend_docker/manage.py test