"""empty message

Revision ID: de42e2e6f12f
Revises: 
Create Date: 2019-02-06 18:11:44.656089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de42e2e6f12f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('registrations', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'registrations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.drop_column('registrations', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
